version: "3.7"

services:
  app:
    build: .
    depends_on:
      - db
    command: "python3 main.py"
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      CAT_API_TOKEN: ${CAT_API_TOKEN}
  
  db:
    image: postgres:14
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment: 
      POSTGRES_PASSWORD: password